version: '2'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./compose/local/wordpress/Dockerfile
    depends_on:
      - mariadb
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 'false'
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./themes/jeo-theme:/var/www/html/wp-content/themes/jeo-theme
      - ./compose/local/wordpress/wp-config.d:/var/www/html/wp-config.d
      - ./compose/local/wordpress/htaccess:/var/www/html/.htaccess
      - ./compose/production/wordpress/php/extra.ini:/usr/local/etc/php/conf.d/extra.ini
  watcher:
    build:
      context: .
      dockerfile: ./compose/local/watcher/Dockerfile
    volumes:
      - ./themes/jeo-theme:/app

  mariadb:
    image: mariadb:10.4
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./compose/local/mariadb/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  mariadb_data:
