name: Generate zip file
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build # Remove or modify this step as needed
      run: |
        cd ${{ github.workspace }}/themes/jeo-theme
        npm install
        npm run production
        cd ${{ github.workspace }}/themes
        ls
        ls jeo-theme
    - uses: actions/upload-artifact@v2
      with:
        name: jeo-theme
        path: |
          ./themes/jeo-theme/*
          !themes/jeo-theme/node_modules
          !themes/jeo-theme/node_modules/*